
#!/bin/zsh


#THE DIFFERNT BETWEEN WHILE COMMAND AND UNTIL COMMAND IS 
# * THE WHILE COMMAND THE STATEMENT IS EXCUTE WHILE IN THE LOOP EXITS WHEN TRUE
# * THE UNTIL COMMAND THE STATEMENT EXCUTE UNTIL THE CONDITION

a=0

until [ ! $a -lt 10 ]
do
	echo $a
	a=`expr $a + 1`
done
